package service

import (
	"encoding/json"
	"github.com/pkg/errors"
	"io/ioutil"
	"net/http"
)

var GetCodeUrl = "http://api.do889.com:81/api/get_message?token=" +
	"MOFnMF7LMkIJwLBBWezpz4D2oqU4VFISw1kIPKzFcQdc8hA2HZpVSOiYDIEQVy924rhIbKVGwxvA9JHuGSGIy+Hz1pl4YODb3Ihngf996Br2+PTJMFns9Kyr8Ck6JD0RlGkno//dwyxrObOXUAqrUIjfDP8XJtbhiqXXGYPGKVg=&project_id=12734&phone_num="

type Autogenerated struct {
	Message string        `json:"message"`
	Code    string        `json:"code"`
	Data    []interface{} `json:"data"`
}

/*
{
    "message": "短信还未到达,请继续获取",
    "data": []
}
*/
func GetCode(mobile string) (code string, err error) {
	resp, err := http.Get(GetCodeUrl + mobile)
	if err != nil {
		return "", err
	}

	defer resp.Body.Close()

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return "", errors.Wrap(err, "receive code fail：应答解析失败")
	}

	a := &Autogenerated{}

	err = json.Unmarshal(body, a)
	if err != nil {
		return "", errors.Wrap(err, "receive code fail：反序列化失败")
	}
	if len(a.Code) == 0 {
		return "", errors.Wrap(err, "receive code fail：验证码不正确")
	}
	return a.Code, nil
}
